# Generated by Django 4.2.4 on 2023-09-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_customuser_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecognizedOrder',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unrecognized_order',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_recognized',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized')], default='recognized', max_length=12),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders_app.order'),
        ),
        migrations.DeleteModel(
            name='UnrecognizedOrder',
        ),
    ]
