# Generated by Django 4.2.4 on 2023-09-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unrecognized_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_app.unrecognizedorder'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_app.order'),
        ),
    ]
