# Generated by Django 4.2.4 on 2023-09-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_recognizedorder_order_is_recognized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='unrecognized_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders_app.unrecognizedorder'),
        ),
    ]
