# Generated by Django 4.2.4 on 2023-09-05 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_recognizedorder_unrecognizedorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='related_order',
            new_name='recognized_order',
        ),
        migrations.AddField(
            model_name='recognizedorder',
            name='status',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized')], default='recognized', max_length=12),
        ),
        migrations.AddField(
            model_name='unrecognizedorder',
            name='status',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized')], default='recognized', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20),
        ),
    ]
